### ISSUE TITLE
upgrade tests for xenial

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#510]
Currently roles system/test.yml are disabled and needs to be updated for xenial.

**Comment by landam** [comment]
Open issues:

```
- name: Test 'gis.lab' DNS records are resolved
  shell: ping -c 1 {{ item }}.gis.lab
  with_items:
    - server
# TBF:
#    - boot
#    - web
```

and

```
# TBF: not working
- name: Test if email to root user was forwarded to test superuser
  shell: >
    sleep 2
    &&
    grep -r "This is a test message sent by GIS.lab test {{ GISLAB_TEST_UNIQUE_STRING }}"
    /mnt/home/test_mail_{{ GISLAB_TEST_UNIQUE_STRING }}/Mail/new
```
